services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Persistencia de datos
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Script de inicialización
    networks:
      - kevin_network

  db_service:
    build: 
      context: ./db_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - kevin_network
    depends_on:
      - db
      
volumes:
  mysql_data:

networks:
  kevin_network:
    driver: bridge